#!/bin/bash

curl --header "Content-Type: application/json" --request DELETE ${1}/sections
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"0\",\"y\":\"0\",\"w\":\"30720\",\"h\":\"4320\",\"app\":{\"url\":\"${1}/app/maps\",\"opacity\":\"0.3\",\"states\":{\"load\":\"London\"}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"500\",\"y\":\"90\",\"w\":\"3947\",\"h\":\"3240\",\"app\":{\"url\":\"${1}/app/images\",\"states\":{\"load\":{\"url\":\"${2}/Intro.png\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"3840\",\"y\":\"3340\",\"w\":\"1781\",\"h\":\"783\",\"app\":{\"url\":\"${1}/app/images\",\"states\":{\"load\":{\"url\":\"${2}/credits.png\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"5824\",\"y\":\"2160\",\"w\":\"3712\",\"h\":\"2160\",\"app\":{\"url\":\"${1}/app/images\",\"states\":{\"load\":{\"url\":\"${2}/TFLjamcamnet.png\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"5800\",\"y\":\"80\",\"w\":\"1150\",\"h\":\"416\",\"app\":{\"url\":\"${1}/app/images\",\"states\":{\"load\":{\"url\":\"${2}/TfL_open_data.png\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"10392\",\"y\":\"1080\",\"w\":\"4175\",\"h\":\"2160\",\"app\":{\"url\":\"${1}/app/images\",\"states\":{\"load\":{\"url\":\"${2}/local_architecture.png\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"5888\",\"y\":\"2288\",\"w\":\"500\",\"h\":\"500\",\"app\":{\"url\":\"${1}/app/images\", \"opacity\":\"0.7\", \"states\":{\"load\":{\"url\":\"${2}/qr-code-jamcamnet.png\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"10581\",\"y\":\"2513\",\"w\":\"500\",\"h\":\"500\",\"app\":{\"url\":\"${1}/app/images\",\"states\":{\"load\":{\"url\":\"${2}/qr-code-repo.png\"}}}}" ${1}/section


open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=1"
open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=2"
open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=3"
open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=4"
open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=5"
open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=6"
open -a "Google Chrome" "${1}/app/images/control.html?oveSectionId=7"
open -a "Google Chrome" "${1}/app/maps/control.html?oveSectionId=0"

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"5824\",\"y\":\"656\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/1.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"6768\",\"y\":\"656\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/2.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"7712\",\"y\":\"656\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/3.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"8656\",\"y\":\"656\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/4.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"5824\",\"y\":\"1440\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/5.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"6768\",\"y\":\"1440\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/6.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"7712\",\"y\":\"1440\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/7.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"8656\",\"y\":\"1440\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/8.mp4\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15424\",\"y\":\"592\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/1.mov\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"16368\",\"y\":\"592\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/2.mov\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"17312\",\"y\":\"592\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/3.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"18256\",\"y\":\"592\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/4.mov\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15424\",\"y\":\"1376\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/5.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"16368\",\"y\":\"1376\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/6.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"17312\",\"y\":\"1376\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/7.mov\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"18256\",\"y\":\"1376\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/debug/8.mov\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15424\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/1.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"16368\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/2.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"17312\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/3.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"18256\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/4.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15424\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/5.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"16368\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/6.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"17312\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/7.mp4\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"18256\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/raw/8.mp4\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15424\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=9&truck=0&person=2\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"16368\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=14&truck=1&person=1\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"17312\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=11&truck=0&person=14\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"18256\",\"y\":\"2224\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=30&truck=2&person=0\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15424\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=2&truck=1&person=13\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"16368\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=1&truck=0&person=10\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"17312\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=4&truck=0&person=11\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"18256\",\"y\":\"3008\",\"w\":\"880\",\"h\":\"720\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/detection.html?car=7&truck=2&person=12\"}}}}" ${1}/section

#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19457\",\"y\":\"360\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/raw.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21334\",\"y\":\"360\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/raw.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"23211\",\"y\":\"360\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/raw.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"25088\",\"y\":\"360\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/normalised.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"26965\",\"y\":\"360\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/normalised.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"28842\",\"y\":\"360\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/normalised.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19457\",\"y\":\"2340\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/raw_central.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21334\",\"y\":\"2340\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/raw_central.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"23211\",\"y\":\"2340\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/raw_central.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"25088\",\"y\":\"2340\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/normalised_central.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"26965\",\"y\":\"2340\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/normalised_central.m4v\"}}}}" ${1}/section
#curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"28842\",\"y\":\"2340\",\"w\":\"1620\",\"h\":\"1620\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/normalised_central.m4v\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/raw.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21120\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/raw.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"23040\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/raw.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"24960\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/normalised.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"26880\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/normalised.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"28800\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/normalised.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/raw_central.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21120\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/raw_central.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"23040\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/raw_central.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"24960\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/cars/normalised_central.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"26880\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/trucks/normalised_central.m4v\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"28800\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/videos\",\"states\":{\"load\":{\"url\":\"${2}/videos/persons/normalised_central.m4v\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"640\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/icon.html?type=car&color=960026\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21120\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"640\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/icon.html?type=truck-moving&color=852e04\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"23040\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"640\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/icon.html?type=walking&color=12256d\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"24960\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"640\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/icon.html?type=car&color=960026\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"26880\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"640\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/icon.html?type=truck-moving&color=852e04\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"28800\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"640\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/icon.html?type=walking&color=12256d\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"240\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Greater%20London&color=0a6400\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Inner%20London&color=0a6400\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21688\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Count%20of%20objects&color=000000\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"27220\",\"y\":\"2160\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Normalised%20level%20of%20objects&color=000000\"}}}}" ${1}/section

curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"10328\",\"y\":\"820\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=System%20Architecture&color=ffffff\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15360\",\"y\":\"320\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Stage%201:%20YOLO%20outputs&color=ffffff\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"15360\",\"y\":\"3770\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Stage%202:%20Overlay%20counter&color=ffffff\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"0\",\"w\":\"1920\",\"h\":\"1920\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${2}/title.html?text=Stage%203:%20Visualisations&color=ffffff\"}}}}" ${1}/section


curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"19200\",\"y\":\"240\",\"w\":\"25\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"21095\",\"y\":\"240\",\"w\":\"50\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"23015\",\"y\":\"240\",\"w\":\"50\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"24900\",\"y\":\"240\",\"w\":\"120\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"26855\",\"y\":\"240\",\"w\":\"50\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"28775\",\"y\":\"240\",\"w\":\"50\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
curl --header "Content-Type: application/json" --request POST --data "{\"space\":\"DOSection\",\"x\":\"30695\",\"y\":\"240\",\"w\":\"25\",\"h\":\"3840\",\"app\":{\"url\":\"${1}/app/html\",\"states\":{\"load\":{\"url\":\"${1}/app/html/data/background/index.html?background=ebead3\"}}}}" ${1}/section
sleep 5

curl -X POST ${1}/app/videos/operation/play?loop=true
